import { Inconsolata } from "next/font/google";
import "./globals.css";
import Provider from "./context/authContext";
import ToasterContext from "./context/ToasterContext";
import StoreProvider from "./components/StoreProvider";
const inconsolata = Inconsolata({ subsets: ["latin"] });

export const metadata = {
  title: "Ot's Coffeee",
  description: "Generated by MEEEEEE",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inconsolata.className} bg-[url(../public/coffee-background.svg)] text-white text-base object-cover`}
      >
        <Provider>
          <StoreProvider>
            <ToasterContext /> {children}
          </StoreProvider>
        </Provider>
      </body>
    </html>
  );
}
